=== disit/icsm/api/schema/sm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Icaro Supervisor & Monitor (ICSM).
   Copyright (C) 2015 DISIT Lab http://www.disit.org - University of Florence

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="configuration">
		<xs:annotation>
			<xs:documentation>Configuration</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="identifier" type="xs:string">
					<xs:annotation>
						<xs:documentation>Internal Identifier</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="xs:string">
					<xs:annotation>
						<xs:documentation>Textual description or URI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Configuration Name</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="bid" type="xs:string">
					<xs:annotation>
						<xs:documentation>Business Id: any other id for business usage</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contacts">
					<xs:annotation>
						<xs:documentation>List of contacts</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Business or System</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="applications" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Icaro Applications</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="application"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="tenants" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Icaro Tenants Application</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="tenant"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="hosts" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Icaro Physical or Vrtual Machines</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="host"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="devices" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Icaro Physical or Virtual Devices</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="device"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="cid" type="xs:integer"/>
		</xs:complexType>
		<xs:keyref name="tenant" refer="cid">
			<xs:selector xpath="tenant"/>
			<xs:field xpath="@cid"/>
		</xs:keyref>
		<xs:keyref name="device" refer="cid">
			<xs:selector xpath="device"/>
			<xs:field xpath="@cid"/>
		</xs:keyref>
		<xs:key name="cid">
			<xs:selector xpath="configuration"/>
			<xs:field xpath="cid"/>
		</xs:key>
		<xs:keyref name="host" refer="cid">
			<xs:selector xpath="host"/>
			<xs:field xpath="@cid"/>
		</xs:keyref>
		<xs:keyref name="application" refer="cid">
			<xs:selector xpath="application"/>
			<xs:field xpath="@cid"/>
		</xs:keyref>
	</xs:element>
	<xs:attribute name="cid" type="xs:integer"/>
	<xs:element name="monitor_info">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metrics">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="metric">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string">
											<xs:annotation>
												<xs:documentation>Name of metric</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="critical_value" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Threshold for critical value</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="warning_value" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Thrashold for warning value</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="args" type="xs:string" minOccurs="0"/>
										<xs:element name="max_check_attempts" type="xs:integer" default="5" minOccurs="0"/>
										<xs:element name="check_interval" type="xs:integer" default="5" minOccurs="0"/>
										<xs:element name="status" default="running" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Running or Stopped o</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="running"/>
													<xs:enumeration value="stopped"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="mode" type="xs:string" default="" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Active or Passive Check: default is Active</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="minfo_id" type="xs:integer"/>
									<xs:attribute name="mid" type="xs:integer"/>
								</xs:complexType>
								<xs:key name="mid">
									<xs:selector xpath="metric"/>
									<xs:field xpath="@mid"/>
								</xs:key>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:integer"/>
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="service"/>
						<xs:enumeration value="host"/>
						<xs:enumeration value="tenant"/>
						<xs:enumeration value="device"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="minfo_id" type="xs:integer"/>
		</xs:complexType>
		<xs:keyref name="moninfo_service" refer="minfo_id">
			<xs:selector xpath="service"/>
			<xs:field xpath="@minfo_id"/>
		</xs:keyref>
		<xs:keyref name="moninfo_tenant" refer="minfo_id">
			<xs:selector xpath="tenant"/>
			<xs:field xpath="@minfo_id"/>
		</xs:keyref>
		<xs:keyref name="moninfo_host" refer="minfo_id">
			<xs:selector xpath="host"/>
			<xs:field xpath="@minfo_id"/>
		</xs:keyref>
		<xs:keyref name="moninfo_device" refer="minfo_id">
			<xs:selector xpath="device"/>
			<xs:field xpath="@minfo_id"/>
		</xs:keyref>
		<xs:keyref name="metric" refer="minfo_id">
			<xs:selector xpath="metric"/>
			<xs:field xpath="@minfo_id"/>
		</xs:keyref>
		<xs:key name="minfo_id">
			<xs:selector xpath="monitor_info"/>
			<xs:field xpath="@minfo_id"/>
		</xs:key>
	</xs:element>
	<xs:element name="service">
		<xs:annotation>
			<xs:documentation>Icaro Service</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string">
					<xs:annotation>
						<xs:documentation>Internal Identifier</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Service Name</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="type" type="xs:string"/>
				<xs:element name="description"/>
				<xs:element name="ip_address" type="xs:string"/>
				<xs:element name="service_group" type="xs:string"/>
				<xs:element name="run_on" type="xs:string">
					<xs:annotation>
						<xs:documentation>Host Id</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="monitor_info"/>
				<xs:element name="port" type="xs:integer" minOccurs="0"/>
				<xs:element name="process_name" type="xs:string" minOccurs="0"/>
				<xs:element name="alias" type="xs:string" minOccurs="0"/>
				<xs:element name="parent" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_user" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_pwd" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="minfo_id" type="xs:integer"/>
			<xs:attribute name="sid" type="xs:integer"/>
			<xs:attribute name="aid" type="xs:integer"/>
		</xs:complexType>
		<xs:key name="sid">
			<xs:selector xpath="service"/>
			<xs:field xpath="@sid"/>
		</xs:key>
	</xs:element>
	<xs:element name="tenant">
		<xs:annotation>
			<xs:documentation>Icaro Tenant</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name">
					<xs:annotation>
						<xs:documentation>Tenant Name (es: XLMS)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="id">
					<xs:annotation>
						<xs:documentation>Tenant Id</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="xs:string" default="">
					<xs:annotation>
						<xs:documentation>A short textual description</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contacts" type="xs:string" default="">
					<xs:annotation>
						<xs:documentation>Email address of resposible</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="monitor_info"/>
				<xs:element name="runOn">
					<xs:annotation>
						<xs:documentation>Application Id referred by Tenant</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="minfo_id" type="xs:integer"/>
			<xs:attribute name="cid" type="xs:integer"/>
			<xs:attribute name="tid" type="xs:integer"/>
		</xs:complexType>
		<xs:key name="tid">
			<xs:selector xpath="tenant"/>
			<xs:field xpath="@tid"/>
		</xs:key>
	</xs:element>
	<xs:element name="application">
		<xs:annotation>
			<xs:documentation>Icaro Application</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name">
					<xs:annotation>
						<xs:documentation>Application Name (es: XLMS)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="id">
					<xs:annotation>
						<xs:documentation>Internal Identifier</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description">
					<xs:annotation>
						<xs:documentation>Textual description or URI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contacts" type="xs:string">
					<xs:annotation>
						<xs:documentation>Email address of resposible</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Application type</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="services">
					<xs:annotation>
						<xs:documentation>Icaro Services</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element ref="service">
								<xs:annotation>
									<xs:documentation>Icaro Service</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="cid" type="xs:integer"/>
			<xs:attribute name="aid" type="xs:integer"/>
		</xs:complexType>
		<xs:keyref name="service" refer="aid">
			<xs:selector xpath="service"/>
			<xs:field xpath="@aid"/>
		</xs:keyref>
		<xs:key name="aid">
			<xs:selector xpath="application"/>
			<xs:field xpath="@aid"/>
		</xs:key>
	</xs:element>
	<xs:element name="host">
		<xs:annotation>
			<xs:documentation>Icaro Physical or Virtual Machine</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string">
					<xs:annotation>
						<xs:documentation>Internal Identifier</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Host Name</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="os" type="xs:string" default="">
					<xs:annotation>
						<xs:documentation>Operating System</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="type" default="host">
					<xs:annotation>
						<xs:documentation>Type of Host: Phiscal Host, or Virtual</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="host"/>
							<xs:enumeration value="guest"/>
							<xs:enumeration value="vmhost"/>
							<xs:enumeration value="HLMhost"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ip_address" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="monitor_ip_address" type="xs:string" minOccurs="0"/>
				<xs:element ref="monitor_info"/>
				<xs:element name="alias" type="xs:string" minOccurs="0"/>
				<xs:element name="parent_host" type="xs:string" minOccurs="0"/>
				<xs:element name="host_group" type="xs:string" minOccurs="0"/>
				<xs:element name="domain_name" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_pwd" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_user" type="xs:string" minOccurs="0"/>
				<xs:element name="description" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="minfo_id" type="xs:integer"/>
			<xs:attribute name="cid" type="xs:integer"/>
			<xs:attribute name="hid" type="xs:integer"/>
		</xs:complexType>
		<xs:key name="hid">
			<xs:selector xpath="host"/>
			<xs:field xpath="@hid"/>
		</xs:key>
	</xs:element>
	<xs:element name="device">
		<xs:annotation>
			<xs:documentation>Single Icaro Physical or Virtual Device</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id">
					<xs:annotation>
						<xs:documentation>Internal Identifier</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="device_type">
					<xs:annotation>
						<xs:documentation>Router, Firewall, ...</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="type">
					<xs:annotation>
						<xs:documentation>Physical (Default), Virtual</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="physical"/>
							<xs:enumeration value="virtual"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ip_address" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="monitor_ip_address" type="xs:string" minOccurs="0"/>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Name of device</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="monitor_info"/>
				<xs:element name="model" type="xs:string" minOccurs="0"/>
				<xs:element name="description" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Textual description</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="port" type="xs:integer" minOccurs="0"/>
				<xs:element name="alias" type="xs:string" minOccurs="0"/>
				<xs:element name="parent_device" type="xs:string" minOccurs="0"/>
				<xs:element name="device_group" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_user" type="xs:string" minOccurs="0"/>
				<xs:element name="auth_pwd" type="xs:string" minOccurs="0"/>
				<xs:element name="domain_name" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="minfo_id" type="xs:integer"/>
			<xs:attribute name="cid" type="xs:integer"/>
			<xs:attribute name="did" type="xs:integer"/>
		</xs:complexType>
		<xs:key name="did">
			<xs:selector xpath="device"/>
			<xs:field xpath="@did"/>
		</xs:key>
	</xs:element>
	<xs:element name="contacts" type="xs:string"/>
</xs:schema>

=== disit/icsm/apps/test/smSysConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="E:/Icaro/data/sm.xsd">
	<identifier>dc01</identifier>
	<description>urn:cloudicaro:DataCenter:01</description>
	<name>data center ICARO</name>
	<contacts />
	<type>System</type>
	<hosts>
		<host>
			<id>host01</id>
			<name>host1</name>
			<os>linux</os>
			<type>host</type>
			<ip_address>192.168.1.124</ip_address>
			<ip_address>192.168.0.125</ip_address>
			<monitor_info type="host">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
					</metric>
				</metrics>
			</monitor_info>
			<host_group>urn:cloudicaro:DataCenter:01</host_group>
			<domain_name>DC01</domain_name>
			<auth_pwd>xxx</auth_pwd>
			<auth_user>root</auth_user>
			<description>urn:cloudicaro:HostMachine:001</description>
		</host>
		<host>
			<id>host02</id>
			<name>host2</name>
			<os>linux</os>
			<type>host</type>
			<ip_address>192.168.1.125</ip_address>
			<monitor_info type="host">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
					</metric>
				</metrics>
			</monitor_info>
			<host_group>urn:cloudicaro:DataCenter:01</host_group>
			<domain_name>DC01</domain_name>
			<auth_pwd>xxx</auth_pwd>
			<auth_user>root</auth_user>
			<description>urn:cloudicaro:HostMachine:002</description>
		</host>
	</hosts>
	<devices>
		<device>
			<id>0001111</id>
			<device_type>ExternalStorage</device_type>
			<type>physical</type>
			<ip_address>192.168.1.100</ip_address>
			<ip_address>192.168.0.101</ip_address>
			<name>exstore01</name>
			<monitor_info type="device">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<args>args</args>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<args>args</args>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
				</metrics>
			</monitor_info>
			<description>urn:cloudicaro:ExternalStorage:001</description>
		</device>
		<device>
			<id>0001112</id>
			<device_type>ExternalStorage</device_type>
			<type>physical</type>
			<ip_address>192.168.1.102</ip_address>
			<ip_address>192.168.0.103</ip_address>
			<name>ex02</name>
			<monitor_info type="device">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
				</metrics>
			</monitor_info>
			<description>urn:cloudicaro:ExternalStorage:002</description>
		</device>
		<device>
			<id>fw1</id>
			<device_type>Firewall</device_type>
			<type>physical</type>
			<ip_address>192.168.1.1</ip_address>
			<ip_address>150.217.15.1</ip_address>
			<name>firewall 1</name>
			<monitor_info type="device">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
				</metrics>
			</monitor_info>
			<model>3COM</model>
			<description>urn:cloudicaro:Firewall:1</description>
		</device>
		<device>
			<id>rt:01</id>
			<device_type>Router</device_type>
			<type>physical</type>
			<ip_address>192.168.1.2</ip_address>
			<ip_address>192.168.0.2</ip_address>
			<name>router 1 to 2</name>
			<monitor_info type="device">
				<metrics>
					<metric>
						<name>avgCPU%1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>3</check_interval>
					</metric>
					<metric>
						<name>avgMem1m</name>
						<critical_value>80</critical_value>
						<warning_value>70</warning_value>
						<max_check_attempts>5</max_check_attempts>
						<check_interval>6</check_interval>
					</metric>
				</metrics>
			</monitor_info>
			<model>3ROUTE</model>
			<description>urn:cloudicaro:Router:1</description>
		</device>
	</devices>
</configuration>

=== disit/icsm/apps/test/smBusConf.xml
<?xml version="1.0" encoding="UTF-8"?><configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"               xsi:noNamespaceSchemaLocation="E:/Icaro/data/sm.xsd">   <identifier>TEST-001</identifier>   <description>urn:cloudicaro:BusinessConfiguration:TEST-001</description>   <name>My Configuration</name>   <contacts>xyz@gmail.com</contacts>   <type>Business</type>   <applications>      <application>         <name>My ECLAP</name>         <id>xlms:001</id>         <description>urn:cloudicaro:XLMS:002</description>         <contacts>xyz@gmail.com;</contacts>         <services>            <service>               <id>AWS:001</id>               <name>Apache Web Server 001</name>               <type>ApacheWebServer</type>               <description>urn:cloudicaro:ApacheWebServer:002</description>               <ip_address/>               <service_group>ApacheWebServer</service_group>               <run_on>vm001</run_on>               <monitor_info type="service">                  <metrics>                     <metric>                        <name>checkHttp</name>                        <args>url:"http://www.ecalp.eu/",contains:"ECLAP"</args>                     </metric>                  </metrics>               </monitor_info>               <port>80</port>            </service>         </services>      </application>   </applications>   <tenants>      <tenant>         <name>OggiWebTenant</name>         <id>001</id>         <description>urn:cloudicaro:OggiWebTenant:001</description>         <contacts>xyz@gmail.com;</contacts>         <monitor_info type="tenant">            <metrics/>         </monitor_info>         <runOn>urn:cloudicaro:OggiWeb:001</runOn>      </tenant>   </tenants>   <hosts>      <host>         <id>vm001</id>         <name>VM001</name>         <os>windowsXP</os>         <type>vmhost</type>         <ip_address>192.168.1.23</ip_address>         <monitor_info type="host">            <metrics>               <metric>                  <name>avgCPU%1m</name>                  <critical_value>80</critical_value>                  <warning_value>70</warning_value>               </metric>            </metrics>         </monitor_info>         <parent_host>urn:cloudicaro:HostMachine:001</parent_host>      </host>   </hosts>   <devices/></configuration>
